avisservice_index:
    path:     /{idService}
    defaults: { _controller: "AvisserviceBundle:AvisService:index" }
    methods:  [GET, POST]

avisservice_show:
    path:     /{idAvis}/show
    defaults: { _controller: "AvisserviceBundle:AvisService:show" }
    methods:  GET

avisservice_new:
    path:     /new/{idService}
    defaults: { _controller: "AvisserviceBundle:AvisService:new" }
    methods:  [GET, POST]

avisservice_edit:
    path:     /{idAvis}/edit
    defaults: { _controller: "AvisserviceBundle:AvisService:edit" }
    methods:  [GET, POST]

avisservice_delete:
    path:     /{idAvis}/delete
    defaults: { _controller: "AvisserviceBundle:AvisService:delete" }
    methods:  DELETE

avisservice_showadmin:
    path:     /{idAvis}/showadmin
    defaults: { _controller: "AvisserviceBundle:AvisService:show" }
    methods:  GET

avisservice_newmobile:
    path:     /newmobile/new
    defaults: { _controller: "AvisserviceBundle:AvisService:newmobile" }

avisservice_mobile:
    path:     /mobile/{idService}
    defaults: { _controller: "AvisserviceBundle:AvisService:mobile" }
    methods:  [GET, POST]

avisservice_deletmobile:
    path:     /mobiledelete/dele
    defaults: { _controller: "AvisserviceBundle:AvisService:deletemobile" }
    methods:  [GET, POST]

avisservice_modfiermobile:
    path:     /mobileupdate/update
    defaults: { _controller: "AvisserviceBundle:AvisService:updatemobile" }
    methods:  [GET, POST]