<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'history.service' shared service.

return $this->services['history.service'] = new \SBC\NotificationsBundle\EventListener\HistoryService($this);
