<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mrad.pusher.notificaitons' shared service.

return $this->services['mrad.pusher.notificaitons'] = new \SBC\NotificationsBundle\Service\PusherService($this);
