service_service:
    resource: "@ServiceBundle/Resources/config/routing/service.yml"
    prefix:   /service

service_homepage:
    path:     /
    defaults: { _controller: ServiceBundle:Default:index }

service_devis:
    path:     /devis/{service}
    defaults: { _controller: ServiceBundle:Service:devis}

service_devis_pdf:
    path:     /devis-pdf/{service}
    defaults: { _controller: ServiceBundle:Service:invoice}


