<?php

namespace ForumBundle\Repository;

/**
 * VerifnbrVueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VerifnbrVueRepository extends \Doctrine\ORM\EntityRepository
{
}
