<?php

namespace ForumBundle\Repository;

/**
 * VerifLikeDislikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VerifLikeDislikeRepository extends \Doctrine\ORM\EntityRepository
{
}
