<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV6kznja\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV6kznja/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerV6kznja.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerV6kznja\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerV6kznja\appDevDebugProjectContainer([
    'container.build_hash' => 'V6kznja',
    'container.build_id' => 'ebe543d4',
    'container.build_time' => 1558648764,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV6kznja');
